# Generated by Django 3.2.8 on 2022-07-08 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0005_auto_20220707_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
